"""Generate Ansible variables and a safe playbook draft from a cluster config.

The MVP fields are not sufficient to deploy a fresh ONTAP cluster, so the
generated playbook is explicitly a *draft* and never presented as runnable.
Secrets are referenced via Ansible Vault placeholders and never embedded.
"""

import yaml

from app.core.models import AnsibleGeneration, ClusterConfig, GeneratedAnsibleFile

_REQUIRED_INPUTS = [
    "cluster management IP address",
    "cluster management netmask and gateway",
    "node management IP addresses (one per node)",
    "node serial numbers (one per node)",
    "ONTAP admin username and password (via ansible-vault)",
    "ONTAP target version / image",
    "license keys (NLF)",
]


def required_inputs(config: ClusterConfig) -> list[str]:
    missing: list[str] = []
    if not config.cluster_name:
        missing.append("cluster name")
    if not config.nodes:
        missing.append("node names")
    missing.extend(_REQUIRED_INPUTS)
    return missing


def generate_vars(config: ClusterConfig) -> str:
    """Deterministic YAML variables file (sorted keys)."""
    data = {
        "cluster_name": config.cluster_name,
        "nodes": [node.name for node in config.nodes],
        "dns_servers": list(config.dns_servers),
        "ntp_servers": list(config.ntp_servers),
        # Placeholders for inputs the MVP has not yet collected.
        "cluster_mgmt_ip": "CHANGE_ME",
        "cluster_mgmt_netmask": "CHANGE_ME",
        "cluster_mgmt_gateway": "CHANGE_ME",
        "node_mgmt_ips": [],
        "node_serial_numbers": [],
        "ontap_admin_username": "admin",
        "ontap_admin_password": "{{ vault_ontap_admin_password }}",
    }
    header = (
        "# Generated by Fieldkit cluster import.\n"
        f"# schema_version: {config.schema_version}\n"
        f"# source: {config.source.filename}\n"
    )
    return header + yaml.safe_dump(data, sort_keys=True)


def generate_playbook(config: ClusterConfig) -> str:
    """A clearly-labelled DRAFT playbook using the netapp.ontap collection."""
    return (
        "# =============================================================================\n"
        "# DRAFT PLAYBOOK - GENERATED BY FIELDKIT CLUSTER IMPORT. DO NOT RUN AS-IS.\n"
        "# The imported workbook provides only cluster name, node names, DNS and NTP.\n"
        "# Additional inputs are required before this can deploy a fresh cluster:\n"
    ) + "".join(f"#   - {item}\n" for item in required_inputs(config)) + (
        "# Verify module arguments against the installed collection:\n"
        "#   ansible-doc netapp.ontap.na_ontap_cluster / na_ontap_dns / na_ontap_ntp\n"
        "# =============================================================================\n"
        "---\n"
        "- name: Deploy fresh NetApp cluster (DRAFT)\n"
        "  hosts: localhost\n"
        "  gather_facts: false\n"
        "  connection: local\n"
        "  collections:\n"
        "    - netapp.ontap\n"
        "  vars_files:\n"
        "    - cluster_vars.yml\n"
        "  vars:\n"
        '    ontap_admin_password: "{{ vault_ontap_admin_password }}"\n'
        "  tasks:\n"
        "    - name: Create the cluster (requires serial numbers + management IPs)\n"
        "      netapp.ontap.na_ontap_cluster:\n"
        '        cluster_name: "{{ cluster_name }}"\n'
        '        cluster_mgmt_ip: "{{ cluster_mgmt_ip }}"\n'
        '        cluster_mgmt_netmask: "{{ cluster_mgmt_netmask }}"\n'
        '        cluster_mgmt_gateway: "{{ cluster_mgmt_gateway }}"\n'
        '        node: "{{ nodes }}"\n'
        '        admin_password: "{{ ontap_admin_password }}"\n'
        "        state: present\n"
        "      no_log: true\n"
        "\n"
        "    - name: Configure DNS\n"
        "      netapp.ontap.na_ontap_dns:\n"
        '        vserver: "{{ cluster_name }}"\n'
        '        name_servers: "{{ dns_servers }}"\n'
        '        hostname: "{{ cluster_mgmt_ip }}"\n'
        '        username: "{{ ontap_admin_username }}"\n'
        '        password: "{{ ontap_admin_password }}"\n'
        "        state: present\n"
        "      no_log: true\n"
        "\n"
        "    - name: Configure NTP\n"
        "      netapp.ontap.na_ontap_ntp:\n"
        '        vserver: "{{ cluster_name }}"\n'
        '        server: "{{ ntp_servers }}"\n'
        '        hostname: "{{ cluster_mgmt_ip }}"\n'
        '        username: "{{ ontap_admin_username }}"\n'
        '        password: "{{ ontap_admin_password }}"\n'
        "        state: present\n"
        "      no_log: true\n"
    )


def generate(config: ClusterConfig) -> AnsibleGeneration:
    """Build the full generation result for a reviewed cluster config."""
    return AnsibleGeneration(
        draft=True,
        variables=GeneratedAnsibleFile(name="cluster_vars.yml", content=generate_vars(config)),
        playbook=GeneratedAnsibleFile(name="deploy_cluster.yml", content=generate_playbook(config)),
        required_inputs=required_inputs(config),
        warnings=[
            "This is a draft: the imported workbook does not include management IPs, "
            "serial numbers, or credentials. Supply them before running."
        ],
    )
